name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Install Dependencies
        run: npm ci

      - name: Load Environment Variables
        run: |
          if [ "$GITHUB_REF_NAME" == "main" ]; then
            cp .env.production $GITHUB_WORKSPACE/.env
          fi

      - name: Build project
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          DEPLOY_OUTPUT=$(netlify deploy --prod --dir=dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_API_TOKEN }})
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
