name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      - name: Install Dependencies
        run: npm ci

      - name: Load Environment Variables
        run: |
          if [ "$GITHUB_REF_NAME" == "main" ]; then
            cp .env.production $GITHUB_WORKSPACE/.env
          fi

      - name: Build project
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      NETLIFY_DEPLOY_URL: ${{ secrets.NETLIFY_DEPLOY_URL }}
    environment:
      name: production
      url: ${{ env.NETLIFY_DEPLOY_URL }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist # Ensure this matches your build output directory

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_API_TOKEN }}
          echo "DEPLOY_OUTPUT=$DEPLOY_OUTPUT" >> $GITHUB_ENV
          echo "$DEPLOY_OUTPUT"
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep -oP 'Website URL: \K\S+')
          echo "NETLIFY_DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Output deployment URL
        run: echo "Deployment URL is $NETLIFY_DEPLOY_URL"

      - name: Set Environment URL
        run: echo "URL=$NETLIFY_DEPLOY_URL" >> $GITHUB_ENV
